# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    hostname: rabbitmq

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  identity_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: identity_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    ports:
      - 1433:1433
    volumes:
      - identity_db_data:/var/opt/mssql
    depends_on:
      - rabbitmq

  customer_write_db:
    image: mongo
    container_name: customer_write_db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - customer_write_db_data:/data/db
    depends_on:
      - rabbitmq

  customer_read_db:
    image: mongo
    container_name: customer_read_db
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - customer_read_db_data:/data/db
    depends_on:
      - rabbitmq
    

volumes:
  rabbitmq_data:
  portainer_data:
  identity_db_data:
  customer_write_db_data:
  customer_read_db_data: